#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GSLX680) += gslX680.o
gslX680-objs := gslX680main.o gsl_point_id_20131111.o

drivers/input/touchscreen/gslx680/gsl_point_id_20131111.o:
	cp drivers/input/touchscreen/gslx680/gsl_point_id_20131111 drivers/input/touchscreen/gslx680/gsl_point_id_20131111.o
